import type { Trilha } from "./types";
import { q } from "./_helpers";
import { videosPiloto } from "./videos-piloto";
import { imagensCategoria, midiaPadraoPorAulaId } from "./midia-catalogo";

// Trilha 3 — excelência operacional e atendimento consultivo com ética.
export const trilhaOperacional: Trilha = {
  id: "operacional",
  numero: 3,
  titulo: "Excelência Operacional e Atendimento Consultivo",
  subtitulo: "Padrão de atendimento 5 estrelas",
  descricao:
    "Acolhimento, escuta ativa, cross-sell ético, organização de loja, planograma e o padrão de encantamento — sem slogans, com excelência real.",
  nivelFaixa: "Todos os níveis",
  icone: "star",
  modulos: [
    {
      id: "atendimento-humano",
      titulo: "Atendimento Humano de Alto Padrão",
      descricao: "Acolhimento, escuta ativa e o roteiro de encantamento ético.",
      imagemHeroUrl: imagensCategoria.atendimentoHumano,
      aulas: [
        {
          id: "acolhimento",
          titulo: "Acolhimento e primeira impressão",
          duracaoMin: 5,
          nivel: "basico",
          videoUrl: videosPiloto.operacionalAbertura,
          imagemHeroUrl: midiaPadraoPorAulaId("acolhimento").imagemHeroUrl,
          imagemProduto: "/imagens/produtos/nivea-protetor-solar.webp",
          resumo: "Como receber o cliente com empatia, atenção e postura profissional.",
          resumoExecutivo: [
            "Contato visual, cumprimento e disponibilidade genuína criam confiança em segundos.",
            "Acolher quem chega ansioso ou constrangido (saúde) é parte do cuidado.",
            "Um sorriso genuíno e o nome da farmácia na abertura já posicionam o atendimento.",
            "Nunca iniciar com 'Pois não?' — parece mecânico. Prefira 'Seja bem-vindo!'",
          ],
          simulacao: {
            cliente: "Cliente entra na farmácia com expressão fechada, andando devagar e olhando as prateleiras sem rumo.",
            falaBoa: '"Olá, seja bem-vindo à Farmácia [nome]! Se precisar de ajuda para encontrar algo ou tiver qualquer dúvida, é só me chamar. Pode ficar à vontade!" (sorriso genuíno, contato visual, tom aberto)',
            falaEvitar: '"Pois não?" (falando de costas, organizando a prateleira, sem olhar para o cliente)',
          },
          comparativo: {
            titulo: "Acolhimento ideal vs. Acolhimento que afasta",
            itens: [
              { nome: "Abertura que acolhe", quando: '"Seja bem-vindo! Como posso te ajudar hoje?" — olho no olho, sorriso, corpo voltado para o cliente.' },
              { nome: "Abertura que afasta", quando: '"Pois não?" — de costas, tom seco, corpo virado para a prateleira. O cliente se sente um incômodo.' },
              { nome: "Cliente com pressa", quando: "Ideal: 'Já vi que você está com pressa, me fala o que precisa que eu resolvo rápido.' Ruim: 'Vai levar alguma coisa?'" },
              { nome: "Cliente inseguro/ansioso", quando: "Ideal: tom calmo, aproximação gradual. Ruim: abordagem invasiva, perguntas fechadas em sequência." },
            ],
          },
          checklist: [
            "Cumprimentar e demonstrar disponibilidade.",
            "Reduzir a ansiedade do cliente.",
            "Manter contato visual e sorriso genuíno.",
            "Nunca atender de costas ou distraído.",
          ],
          quandoChamarFarmaceutico: ["Quando a demanda exigir orientação clínica."],
          errosComuns: ["Ignorar o cliente que aguarda.", "Demonstrar pressa ou desinteresse."],
          quiz: [
            q(
              "A primeira impressão no balcão é construída principalmente por:",
              [
                "Preço",
                "Acolhimento e disponibilidade genuína",
                "Tamanho da loja",
                "Quantidade de produtos",
              ],
              1,
              "Empatia e disponibilidade criam confiança imediata.",
            ),
            q(
              "Qual abordagem de abertura é mais adequada para um cliente idoso?",
              [
                '"Fala, chefia! Qual é a boa?"',
                '"Boa tarde! Seja bem-vindo. Pode vir com calma que estou aqui para ajudar."',
                '"Rápido, o que você quer?"',
                '"Pois não, meu filho?"',
              ],
              1,
              "Cliente idoso precisa de calma, pausa e tom respeitoso na abordagem.",
            ),
            q(
              "Como lidar com um cliente que entra na farmácia claramente irritado?",
              [
                "Ignorar até ele se acalmar",
                "Abordar com tom neutro e respeitoso, sem sorriso forçado: 'Boa tarde, fique à vontade'",
                "Perguntar na hora o que ele quer",
                "Chamar o gerente imediatamente",
              ],
              1,
              "Cliente irritado precisa de espaço e respeito. Abordagem neutra e calma reduz a tensão sem ser invasiva.",
            ),
            q(
              "Por que 'Pois não?' não é uma boa abertura?",
              [
                "Porque é muito formal",
                "Porque soa mecânico e não estabelece conexão genuína",
                "Porque é muito longo",
                "Porque o cliente não entende",
              ],
              1,
              "'Pois não?' é uma muleta do varejo que não cria rapport. Substitua por algo mais acolhedor e pessoal.",
            ),
          ],
          xp: 50,
        },
        {
          id: "escuta-ativa",
          titulo: "Escuta ativa e triagem da necessidade",
          duracaoMin: 6,
          nivel: "intermediario",
          imagemHeroUrl: midiaPadraoPorAulaId("escuta-ativa").imagemHeroUrl,
          resumo: "Perguntar, repetir o problema com clareza e entender a real necessidade.",
          resumoExecutivo: [
            "Escutar mais do que falar; perguntas abertas revelam a necessidade real.",
            "Repetir o problema com clareza confirma o entendimento ('Então você precisa de...').",
            "Validar o sentimento do cliente antes de solucionar cria vínculo.",
            "Nunca presumir a necessidade — pergunte sempre.",
          ],
          simulacao: {
            cliente: "Cliente: 'quero algo para a pele'.",
            falaBoa:
              "Para te indicar o ideal: é para o rosto ou corpo? Tem alguma sensibilidade ou está em tratamento? Assim acerto a textura certa para você.",
            falaEvitar: "Leva esse creme aqui.",
          },
          comparativo: {
            titulo: "Escuta ativa vs. Escuta passiva",
            itens: [
              { nome: "Escuta ativa", quando: "Faz perguntas abertas, parafraseia, valida sentimentos. 'Então você sente desconforto após as refeições, é isso?'" },
              { nome: "Escuta passiva", quando: "Apenas ouve sem reagir, já pensando na resposta. 'Hum... tá. Leva esse aqui.'" },
              { nome: "Triagem eficaz", quando: "Mapeia: o quê, desde quando, já tentou algo, tem alergia? 'E essa coceira começou depois de usar algum produto novo?'" },
              { nome: "Triagem superficial", quando: "Pergunta única e já indica. 'É alergia? Então leva essa pomada.' — 50% de chance de errar." },
            ],
          },
          checklist: [
            "Fazer perguntas abertas.",
            "Repetir o problema para confirmar.",
            "Só então indicar.",
            "Validar o sentimento do cliente.",
          ],
          quandoChamarFarmaceutico: ["Quando a triagem revelar sinais de alerta."],
          errosComuns: ["Indicar antes de entender a necessidade."],
          quiz: [
            q(
              "Escuta ativa significa, sobretudo:",
              [
                "Falar mais que o cliente",
                "Perguntar e confirmar a real necessidade",
                "Empurrar o mais vendido",
                "Apressar o atendimento",
              ],
              1,
              "Escuta ativa é entender de verdade antes de indicar.",
            ),
            q(
              "Qual pergunta ajuda a fazer uma triagem mais completa?",
              [
                '"É para você?"',
                '"Desde quando você está com esse sintoma? Já tentou algum produto?"',
                '"Vai levar o genérico?"',
                '"É com ou sem receita?"',
              ],
              1,
              "Perguntas investigativas abertas revelam o cenário completo e evitam erros de indicação.",
            ),
            q(
              "Depois que o cliente explica o problema, qual o próximo passo da escuta ativa?",
              [
                "Ir direto para a gôndola pegar o produto",
                "Parafrasear: 'Então, se eu entendi direito, você está sentindo...'",
                "Perguntar o preço máximo que ele quer pagar",
                "Anotar o nome do cliente no cadastro",
              ],
              1,
              "Parafrasear mostra que você ouviu de verdade e confirma se entendeu corretamente.",
            ),
            q(
              "Qual erro mais comum na triagem de necessidade?",
              [
                "Perguntar demais",
                "Indicar um produto antes de entender o problema",
                "Anotar as informações",
                "Chamar o farmacêutico",
              ],
              1,
              "Indicar antes de entender é o erro número 1 do balcão. Gera troca, insatisfação e desconfiança.",
            ),
          ],
          xp: 65,
        },
        {
          id: "encantamento",
          titulo: "Roteiro de encantamento ético",
          duracaoMin: 6,
          nivel: "intermediario",
          imagemHeroUrl: midiaPadraoPorAulaId("encantamento").imagemHeroUrl,
          resumo:
            "Acolher, ouvir, orientar com segurança, sugerir valor real, checar entendimento e encaminhar.",
          resumoExecutivo: [
            "Padrão de excelência: acolher → ouvir → repetir o problema → orientar com segurança → sugerir valor real → checar entendimento → fechar com confiança → encaminhar quando cabível.",
            "Encantamento não é slogan: é cuidado, comunicação e uso racional.",
            "Checar entendimento evita que o cliente saia com dúvida — e dúvida gera não-adesão.",
            "O fechamento com confiança inclui: 'Ficou alguma dúvida? Pode perguntar.'",
          ],
          simulacao: {
            cliente: "Cliente compra um anti-inflamatório e parece confuso sobre o horário de tomar.",
            falaBoa: '"Você vai tomar esse medicamento de 8 em 8 horas, sempre após as refeições para evitar desconforto no estômago. Vou anotar aqui na caixa os horários: 8h, 16h e 22h. Ficou claro? Pode repetir pra eu confirmar?"',
            falaEvitar: '"Toma de 8 em 8 horas. Próximo!" (já virando para o próximo cliente sem checar entendimento)',
          },
          comparativo: {
            titulo: "Roteiro de encantamento completo vs. Atendimento básico",
            itens: [
              { nome: "Acolhimento", quando: "Encantamento: 'Olá! Seja bem-vindo.' ↔ Básico: 'Pois não?'" },
              { nome: "Ouvir e repetir", quando: "Encantamento: paráfrase + validação. ↔ Básico: escuta pela metade e já indica." },
              { nome: "Orientação", quando: "Encantamento: explica com clareza, usa linguagem simples. ↔ Básico: fala o nome técnico e entrega." },
              { nome: "Checagem final", quando: "Encantamento: 'Ficou alguma dúvida?' ↔ Básico: já entrega a nota e encerra." },
            ],
          },
          checklist: [
            "Seguir as etapas do roteiro.",
            "Checar o entendimento ao final.",
            "Encaminhar ao farmacêutico quando cabível.",
            "Usar linguagem simples e acessível.",
          ],
          quandoChamarFarmaceutico: ["Quando a orientação ultrapassar o autocuidado."],
          errosComuns: ["Pular a checagem de entendimento."],
          quiz: [
            q(
              "Qual etapa NÃO faz parte do encantamento ético?",
              [
                "Acolher e ouvir",
                "Sugerir valor real",
                "Empurrar o item mais caro sem necessidade",
                "Checar entendimento",
              ],
              2,
              "Empurrar produto sem necessidade contraria o padrão ético de encantamento.",
            ),
            q(
              "Por que checar o entendimento do cliente é essencial?",
              [
                "Para ganhar tempo",
                "Para garantir que o cliente use o medicamento corretamente e adira ao tratamento",
                " Para preencher o relatório da farmácia",
                "Para impressionar o gerente",
              ],
              1,
              "Checar o entendimento reduz erros de medicação, aumenta a adesão e evita que o cliente volte com dúvidas.",
            ),
            q(
              "Qual a melhor forma de encerrar um atendimento com encantamento?",
              [
                '"Tchau, próximo!"',
                '"Ficou alguma dúvida? Pode me perguntar. E lembre-se: estamos aqui para o que você precisar!"',
                '"Pode ir lá no caixa."',
                '"Leu a bula em casa."',
              ],
              1,
              "Um encerramento que convida o cliente a tirar dúvidas demonstra cuidado genuíno e disponibilidade.",
            ),
            q(
              "O que fazer quando o cliente não entendeu a orientação mesmo após a explicação?",
              [
                "Repetir a mesma explicação mais alto",
                "Simplificar a linguagem e usar exemplos práticos. Se necessário, chamar o farmacêutico",
                "Dizer para ler a bula",
                "Ignorar e ir para o próximo",
              ],
              1,
              "Se o cliente não entendeu, a responsabilidade é do atendente em simplificar. Chamar o farmacêutico é uma alternativa válida.",
            ),
          ],
          xp: 70,
        },
        {
          id: "cross-sell",
          titulo: "Cross-sell ético e bundles de bem-estar",
          duracaoMin: 6,
          nivel: "avancado",
          videoUrl: "https://www.youtube.com/watch?v=3PmVJQUCm4E",
          imagemHeroUrl: midiaPadraoPorAulaId("cross-sell").imagemHeroUrl,
          resumo: "Sugerir itens complementares que fazem sentido — nunca empurrar.",
          resumoExecutivo: [
            "Cross-sell ético parte da necessidade: protetor solar + pós-sol, antibiótico + orientação de adesão.",
            "Bundles de bem-estar (rotina de pele, kit do bebê) agregam valor quando coerentes.",
            "Nunca condicionar a venda principal a um item extra.",
            "Ofereça no máximo 2 complementos — mais que isso vira empurroterapia.",
          ],
          simulacao: {
            cliente: "Cliente comprando fralda e pomada para o bebê.",
            falaBoa:
              "Posso sugerir um lenço sem álcool que combina com a rotina do bebê? Ajuda a prevenir assaduras junto com a pomada.",
            falaEvitar: "Leva mais 5 itens que estão em promoção.",
          },
          comparativo: {
            titulo: "Cross-sell ético vs. Empurroterapia",
            itens: [
              { nome: "Cross-sell ético", quando: "Oferece complemento com relação lógica. Ex: antialérgico + soro fisiológico para lavagem nasal." },
              { nome: "Empurroterapia", quando: "Oferece itens aleatórios sem conexão. Ex: 'Já que vai levar o xarope, leva também esse perfume.'" },
              { nome: "Quantidade ideal", quando: "Ético: 1-2 complementos. Empurroterapia: 3+ itens empilhados no balcão." },
              { nome: "Resposta ao 'não'", quando: "Ético: aceita na hora. Empurroterapia: insiste, argumenta, faz o cliente se sentir culpado." },
            ],
          },
          checklist: ["Sugerir complementos coerentes.", "Respeitar o 'não' do cliente.", "Limitar a 2 ofertas por atendimento."],
          quandoChamarFarmaceutico: ["Quando o complemento envolver decisão clínica."],
          errosComuns: ["Empurrar itens sem relação com a necessidade."],
          quiz: [
            q(
              "Cross-sell ético é:",
              [
                "Empurrar o máximo de itens",
                "Sugerir complementos que fazem sentido para a necessidade",
                "Condicionar a venda principal",
                "Vender o mais caro sempre",
              ],
              1,
              "Cross-sell ético agrega valor real, partindo da necessidade do cliente.",
            ),
            q(
              "Um exemplo de cross-sell ético no balcão é:",
              [
                '"Leva esse xampu também, está em promoção" (cliente comprando fralda)',
                '"Já que você está levando o antialérgico, esse soro nasal ajuda a complementar o tratamento"',
                '"Só hoje: leve 3 e pague 2 em qualquer produto"',
                '"Todo mundo que compra esse remédio leva também esse suplemento"',
              ],
              1,
              "O cross-sell ético tem conexão lógica com a necessidade do cliente — antialérgico + soro nasal se complementam.",
            ),
            q(
              "Quantos itens de cross-sell são recomendados no máximo por atendimento?",
              [
                "Quantos o cliente aceitar",
                "1 a 2 itens no máximo",
                "5 itens",
                "Nenhum — cross-sell nunca é recomendado",
              ],
              1,
              "Mais de 2 ofertas vira empurroterapia. O cliente se sente pressionado e perde a confiança.",
            ),
            q(
              "Qual a melhor reação quando o cliente recusa o cross-sell?",
              [
                "Insistir mostrando os benefícios",
                "Aceitar na hora: 'Sem problemas! Ficou só com o que precisa mesmo?'",
                "Mostrar um produto mais barato",
                "Perguntar por que ele não quer",
              ],
              1,
              "Aceitar o 'não' graciosamente é essencial. Insistir quebra o rapport e a confiança construída.",
            ),
          ],
          xp: 75,
        },
      ],
    },
    {
      id: "operacao-loja",
      titulo: "Operação e Organização de Loja",
      descricao: "Rotina, planograma, exposição e gestão de picos sazonais.",
      imagemHeroUrl: imagensCategoria.operacionalLoja,
      aulas: [
        {
          id: "rotina-organizacao",
          titulo: "Rotina, pontualidade e organização",
          duracaoMin: 5,
          nivel: "basico",
          videoUrl: "https://www.youtube.com/watch?v=3PmVJQUCm4E",
          imagemHeroUrl: midiaPadraoPorAulaId("rotina-organizacao").imagemHeroUrl,
          resumo: "Disciplina operacional: abertura, reposição, validade e limpeza.",
          resumoExecutivo: [
            "Rotina previsível reduz erros: conferência de validade (PVPS), reposição e limpeza.",
            "Pontualidade e trabalho em equipe sustentam o atendimento.",
            "Checklist de abertura e fechamento evita esquecimentos que geram perdas.",
            "Conferência diária de termolábeis (geladeira) é obrigatória e salva vidas.",
          ],
          simulacao: {
            cliente: "Fiscal sanitário chega para uma inspeção de rotina.",
            falaBoa: '"Bom dia! Seja bem-vindo. Pode ficar à vontade para realizar a inspeção. Aqui estão nossos registros de temperatura e controle de validade, todos em dia."',
            falaEvitar: '"Ah, é inspeção? Pera aí que vou avisar o farmacêutico... (começa a esconder produtos vencidos às pressas)"',
          },
          comparativo: {
            titulo: "Rotina organizada vs. Rotina desorganizada",
            itens: [
              { nome: "Checklist de abertura", quando: "Organizado: conferência de validade, limpeza, ajuste de precificação. Desorganizado: abre a porta e começa a atender." },
              { nome: "Conferência de termolábeis", quando: "Organizado: temperatura registrada 2x ao dia. Desorganizado: 'A geladeira está ligada, tá bom.'" },
              { nome: "Reposição", quando: "Organizado: PVPS — primeiro a vencer, primeiro a sair. Desorganizado: repõe o novo na frente do antigo." },
              { nome: "Equipe", quando: "Organizado: reunião rápida de 5 min no início do turno. Desorganizado: cada um faz o que quer." },
            ],
          },
          checklist: [
            "Conferir validades (primeiro a vencer, primeiro a sair).",
            "Manter reposição e limpeza.",
            "Verificar temperatura de termolábeis.",
            "Seguir checklist de abertura e fechamento.",
          ],
          quandoChamarFarmaceutico: ["Dúvidas de armazenamento de termolábeis e controlados."],
          errosComuns: ["Repor sem checar validade."],
          quiz: [
            q(
              "PVPS (primeiro a vencer, primeiro a sair) serve para:",
              [
                "Vender o mais novo primeiro",
                "Evitar perdas por vencimento",
                "Aumentar o preço",
                "Nada",
              ],
              1,
              "PVPS prioriza a saída dos itens com validade mais próxima, reduzindo perdas.",
            ),
            q(
              "Qual a frequência recomendada para conferência de temperatura da geladeira de termolábeis?",
              [
                "Uma vez por semana",
                "Duas vezes ao dia (manhã e tarde)",
                "Uma vez por mês",
                "Só quando chega entrega nova",
              ],
              1,
              "Termolábeis exigem monitoramento 2x ao dia para garantir a eficácia dos medicamentos.",
            ),
            q(
              "O que fazer ao encontrar um medicamento com validade vencida na prateleira?",
              [
                "Colocar na frente para vender rápido",
                "Separar, registrar como perda e descartar conforme legislação",
                "Devolver ao fornecedor sem registro",
                "Ignorar e repor na mesma frente",
              ],
              1,
              "Produto vencido deve ser imediatamente segregado, registrado e descartado conforme as normas da ANVISA.",
            ),
            q(
              "Qual o principal benefício de um checklist de abertura de loja?",
              [
                "Atrasar a abertura",
                "Padronizar a rotina e evitar esquecimentos que geram perdas e riscos",
                "Aumentar a burocracia",
                "Substituir o farmacêutico",
              ],
              1,
              "Checklist padronizado reduz erros humanos e garante que nenhuma etapa crítica seja pulada.",
            ),
          ],
          xp: 50,
        },
        {
          id: "planograma",
          titulo: "Planograma e exposição",
          duracaoMin: 6,
          nivel: "intermediario",
          videoUrl: "https://www.youtube.com/watch?v=G77tZACxZPQ",
          imagemHeroUrl: midiaPadraoPorAulaId("planograma").imagemHeroUrl,
          resumo: "Como organizar categorias e gôndolas para facilitar a jornada do cliente.",
          resumoExecutivo: [
            "Organização por categoria (medicamentos, beleza, higiene, mamãe e bebê, dermocosméticos) facilita o autosserviço assistido.",
            "Itens de maior giro e sazonais em destaque; controlados sempre em área restrita.",
            "Exposição ao nível dos olhos vende até 30% mais que prateleiras inferiores.",
            "Cross-merchandising: posicionar produtos complementares próximos (xarope + mel, protetor + pós-sol).",
          ],
          simulacao: {
            cliente: "Cliente procurando xarope infantil e não encontra porque está misturado com xaropes de adulto.",
            falaBoa: '"Vou te mostrar onde estão. E já aproveito para organizar melhor — obrigado pelo toque! Infantis devem ficar separados para facilitar a busca."',
            falaEvitar: '"Está tudo misturado mesmo, vai olhando aí."',
          },
          comparativo: {
            titulo: "Planograma eficiente vs. Gôndola bagunçada",
            itens: [
              { nome: "Categorias", quando: "Eficiente: separadas por segmento (MIP, dermocosméticos, bebê, higiene). Bagunçado: tudo misturado." },
              { nome: "Altura de exposição", quando: "Eficiente: itens de maior margem na altura dos olhos. Bagunçado: itens aleatórios em qualquer lugar." },
              { nome: "Cross-merchandising", quando: "Eficiente: itens complementares próximos. Bagunçado: cada item isolado sem relação." },
              { nome: "Validade à vista", quando: "Eficiente: PVPS seguido, validade visível. Bagunçado: produtos vencidos misturados." },
            ],
          },
          checklist: [
            "Agrupar por categoria lógica.",
            "Destacar sazonais.",
            "Manter controlados em área restrita.",
            "Posicionar itens de alto giro na altura dos olhos.",
          ],
          quandoChamarFarmaceutico: ["Posicionamento de itens sob controle especial."],
          errosComuns: ["Expor controlados em área de autosserviço."],
          quiz: [
            q(
              "Onde devem ficar os medicamentos controlados?",
              [
                "Na vitrine de autosserviço",
                "Em área restrita/atrás do balcão",
                "Na entrada",
                "Misturados com MIP",
              ],
              1,
              "Controlados ficam em área restrita, nunca em autosserviço.",
            ),
            q(
              "O que é cross-merchandising no contexto de farmácia?",
              [
                "Vender produtos de diferentes marcas",
                "Posicionar produtos complementares próximos para estimular a compra",
                "Trocar produtos de lugar toda semana",
                "Aumentar o preço de produtos sazonais",
              ],
              1,
              "Cross-merchandising posiciona itens que se complementam (ex: protetor solar + pós-sol) para facilitar a decisão de compra.",
            ),
            q(
              "Em qual altura da prateleira um item vende até 30% mais?",
              [
                "Prateleira do chão",
                "Altura dos olhos",
                "Prateleira superior (acima da cabeça)",
                "Não faz diferença",
              ],
              1,
              "A altura dos olhos é a posição nobre da gôndola. Produtos nessa altura têm até 30% mais saída.",
            ),
            q(
              "Qual categoria de produto merece destaque sazonal no verão?",
              [
                "Xaropes e antigripais",
                "Protetores solares e repelentes",
                "Hidratantes corporais pesados",
                "Vitaminas do complexo B",
              ],
              1,
              "Verão = alta demanda por fotoproteção e repelentes. São itens que devem ganhar destaque na exposição.",
            ),
          ],
          xp: 60,
        },
        {
          id: "sazonalidade-equipe",
          titulo: "Picos sazonais e trabalho em equipe",
          duracaoMin: 5,
          nivel: "intermediario",
          videoUrl: "https://www.youtube.com/watch?v=3PmVJQUCm4E",
          imagemHeroUrl: midiaPadraoPorAulaId("sazonalidade-equipe").imagemHeroUrl,
          resumo: "Antecipar demandas do calendário e atuar em equipe nos picos.",
          resumoExecutivo: [
            "Inverno: respiratórios e gripe; verão: fotoproteção e repelentes; campanhas de vacinação.",
            "Equipe alinhada distribui filas e mantém o padrão de atendimento.",
            "Antecipar estoque sazonal evita ruptura e perda de clientes.",
            "Comunicação entre turnos é essencial para alinhar prioridades do dia.",
          ],
          simulacao: {
            cliente: "Dia de pico no inverno, fila no balcão, clientes tossindo e com pressa.",
            falaBoa: '"Pessoal, vamos dividir: João, foca no atendimento da fila de medicamentos. Maria, organiza os antigripais que estão acabando. Eu cuido da fila de dermocosméticos. Se alguém precisar de farmacêutico, sinaliza para o Dr. Carlos."',
            falaEvitar: '"Gente, tá cheio! Cada um faz o que puder aí!" (sem coordenação, atendentes se atropelando)',
          },
          comparativo: {
            titulo: "Gestão de picos sazonais: preparado vs. Despreparado",
            itens: [
              { nome: "Estoque", quando: "Preparado: estoque reforçado 15 dias antes do pico. Despreparado: 'Acabou e o fornecedor não entregou.'" },
              { nome: "Equipe", quando: "Preparado: escalas ajustadas com reforço nos horários críticos. Despreparado: equipe enxuta no pior momento." },
              { nome: "Comunicação", quando: "Preparado: briefing rápido no início do turno. Despreparado: cada um descobre o que fazer na hora." },
              { nome: "Exposição", quando: "Preparado: materiais sazonais em destaque com antecedência. Despreparado: corre para montar vitrine na véspera." },
            ],
          },
          checklist: ["Antecipar estoque sazonal.", "Dividir tarefas nos picos.", "Fazer briefing de início de turno.", "Monitorar ruptura de itens sazonais."],
          quandoChamarFarmaceutico: ["Campanhas de vacinação e serviços clínicos."],
          errosComuns: ["Ser pego de surpresa por sazonalidade previsível."],
          quiz: [
            q(
              "No inverno, aumenta a procura por:",
              [
                "Repelentes",
                "Sintomáticos respiratórios e gripe",
                "Protetor solar apenas",
                "Esmaltes",
              ],
              1,
              "O inverno eleva a demanda por itens respiratórios e gripais.",
            ),
            q(
              "Qual a principal consequência de não antecipar o estoque sazonal?",
              [
                "Clientes compram mais caro",
                "Ruptura de estoque e perda de clientes — cliente vai para o concorrente",
                "Sobra de produtos",
                "Funcionários trabalham menos",
              ],
              1,
              "Ruptura sazonal é evitável. Antecipar o pedido com base no calendário é obrigação da gestão de loja.",
            ),
            q(
              "Durante um pico de atendimento, a prioridade da equipe deve ser:",
              [
                "Cada um cuidar da sua tarefa individual",
                "Dividir funções estrategicamente: um na fila, um na reposição, um no suporte",
                "Fechar a loja temporariamente",
                "Todos atenderem ao mesmo tempo sem divisão",
              ],
              1,
              "Divisão estratégica de funções mantém a qualidade do atendimento mesmo em horários de pico.",
            ),
            q(
              "Qual ferramenta ajuda a equipe a se preparar para sazonalidades?",
              [
                "Planilha de última hora",
                "Calendário sazonal com previsão de demanda por período",
                "Palpite do gerente",
                "Relatório do ano anterior (se existir)",
              ],
              1,
              "Um calendário sazonal com histórico de demanda permite antecipar compras, escalas e exposição com semanas de antecedência.",
            ),
          ],
          xp: 55,
        },
      ],
    },
  ],
};
